apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-api
  namespace: myapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor-api
  template:
    metadata:
      labels:
        app: processor-api
    spec:
      containers:
      - name: processor-api
        image: gcr.io/$PROJECT_ID/processor_api:latest  # Always uses the latest image
        imagePullPolicy: Always  # Ensures Kubernetes always pulls the latest image
        ports:
        - containerPort: 6001
        env:
        - name: VOLUME_MOUNT_PATH
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: VOLUME_MOUNT_PATH
        volumeMounts:
        - name: shared-storage
          mountPath: "/mnt/data"
        resources:
          requests:
            cpu: "100m"  # Reduced CPU request
            memory: "128Mi"  # Reduced memory request
          limits:
            cpu: "500m"  # Adjusted CPU limit
            memory: "512Mi"  # Adjusted memory limit
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: filestore-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: processor-api-service
  namespace: myapp-namespace
spec:
  type: LoadBalancer
  selector:
    app: processor-api
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001