steps:
  # Build Docker image for processor_api
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/processor_api:latest', './processor_api']

  # Push Docker image for processor_api
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/processor_api:latest']

  # Set up kubectl and authenticate with GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'myapp-gke-cluster'
      - '--zone'
      - 'us-central1-a'
    id: 'Set up kubectl'

  # Deploy the latest image to GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'kubectl'
      - 'apply'
      - '-f'
      - 'processor_api/k8s/processor-api-deployment.yaml'
    id: 'Deploy processor_api to GKE'

images:
  - 'gcr.io/$PROJECT_ID/processor_api:latest'

options:
  logging: CLOUD_LOGGING_ONLY