apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-api
  namespace: myapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor-api
  template:
    metadata:
      labels:
        app: processor-api
    spec:
      containers:
      - name: processor-api
        image: kandarpincanada/processor-api:1.0.1
        ports:
        - containerPort: 6001
        env:
        - name: VOLUME_MOUNT_PATH
          value: "/mnt/data"
        volumeMounts:
        - name: shared-storage
          mountPath: "/mnt/data"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m" 
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: processor-api-service
  namespace: myapp-namespace
spec:
  type: ClusterIP
  selector:
    app: processor-api
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001