apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
  namespace: myapp-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"