steps:
  # Build Docker image for validator_api
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/validator_api:$COMMIT_SHA', './validator_api']

  # Push Docker image for validator_api
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/validator_api:$COMMIT_SHA']

  # Set up kubectl and authenticate with GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'myapp-gke-cluster'
      - '--zone'
      - 'us-central1-a'
    id: 'Set up kubectl'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'sh'
      - '-c'
      - |
          # Use envsubst instead of sed for more reliable variable substitution
          export COMMIT_SHA=$COMMIT_SHA
          envsubst < validator_api/k8s/validator-api-deployment.yaml > /tmp/deployment.yaml
          cat /tmp/deployment.yaml  # Debug: print the file to verify content
          kubectl apply -f /tmp/deployment.yaml
    id: 'Deploy validator_api to GKE'

images:
  - 'gcr.io/$PROJECT_ID/validator_api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY