apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-api
  namespace: myapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-api
  template:
    metadata:
      labels:
        app: validator-api
    spec:
      containers:
      - name: validator-api
        image: gcr.io/spry-gateway-453614-i1/validator_api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
        env:
        - name: PROCESSOR_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: PROCESSOR_API_BASE_URL
        - name: VOLUME_MOUNT_PATH
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: VOLUME_MOUNT_PATH
        volumeMounts:
        - name: shared-storage
          mountPath: "/kandarp_PV_dir"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: validator-api-service
  namespace: myapp-namespace
spec:
  type: LoadBalancer
  selector:
    app: validator-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000