apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-api
  namespace: myapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-api
  template:
    metadata:
      labels:
        app: validator-api
    spec:
      containers:
      - name: validator-api
        image: gcr.io/spry-gateway-453614-i1/validator_api:${_COMMIT_SHA}
        ports:
        - containerPort: 6000
        env:
        - name: PROCESSOR_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: PROCESSOR_API_BASE_URL
        - name: VOLUME_MOUNT_PATH
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: VOLUME_MOUNT_PATH
        volumeMounts:
        - name: shared-storage
          mountPath: "/mnt/data"
        resources:
          requests:
            cpu: "100m"  # Reduced CPU request
            memory: "128Mi"  # Reduced memory request
          limits:
            cpu: "500m"  # Adjusted CPU limit
            memory: "512Mi"  # Adjusted memory limit
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: filestore-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: validator-api-service
  namespace: myapp-namespace
spec:
  type: ClusterIP
  selector:
    app: validator-api
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000