apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:  # Correct field for NFS configuration
    server: <FILESTORE_IP_ADDRESS>  # Replace with your Filestore instance IP
    path: /myapp_share              # Replace with your Filestore file share name
  storageClassName: manual