apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore-pvc
  namespace: myapp-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: manual
  volumeName: filestore-pv