apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: pd.csi.storage.k8s.io
    volumeHandle: projects/spry-gateway-453614-i1/zones/us-central1-a/disks/myapp-disk
    fsType: ext4
  mountOptions:
    - discard