name: Terraform Setup, Build, Push to GAR, and Deploy GKE

on:
  push:
    branches:
      - main

jobs:
  terraform-setup:
    name: "Setup Infrastructure with Terraform"
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Google Cloud Credentials
      - name: Setup Google Cloud Credentials
        run: echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-sa-key.json

      # Step 3: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 4: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # Step 5: Initialize Terraform
      - name: Terraform Init
        run: |
          cd terraform
          terraform init -backend-config="bucket=${{ secrets.TF_BUCKET }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-sa-key.json

      # Step 6: Check if Resources Exist and Import into Terraform State
      - name: Check if Resources Exist and Import into Terraform State
        run: |
          cd terraform
          
          # Create a script to check and import all resources
          cat > import_resources.sh << 'EOF'
          #!/bin/bash
          set -e
          
          # Check and import GKE cluster
          if gcloud container clusters describe myapp-gke-cluster --zone us-central1-a --project ${{ secrets.PROJECT_ID }} > /dev/null 2>&1; then
            echo "Cluster exists. Importing into Terraform state..."
            terraform import google_container_cluster.primary projects/${{ secrets.PROJECT_ID }}/locations/us-central1-a/clusters/myapp-gke-cluster || echo "Already in state or import failed"
          else
            echo "Cluster does not exist. Will be created."
            terraform state rm google_container_cluster.primary || true
          fi
          
          # Check and import node pool
          if gcloud container node-pools describe myapp-node-pool --cluster myapp-gke-cluster --zone us-central1-a --project ${{ secrets.PROJECT_ID }} > /dev/null 2>&1; then
            echo "Node pool exists. Importing into Terraform state..."
            terraform import google_container_node_pool.primary_nodes projects/${{ secrets.PROJECT_ID }}/locations/us-central1-a/clusters/myapp-gke-cluster/nodePools/myapp-node-pool || echo "Already in state or import failed"
          else
            echo "Node pool does not exist. Will be created."
            terraform state rm google_container_node_pool.primary_nodes || true
          fi
          
          # Check and import Artifact Registry
          if gcloud artifacts repositories describe myapp-repo --location us-central1 --project ${{ secrets.PROJECT_ID }} > /dev/null 2>&1; then
            echo "Artifact registry exists. Importing into Terraform state..."
            terraform import google_artifact_registry_repository.myapp_repo projects/${{ secrets.PROJECT_ID }}/locations/us-central1/repositories/myapp-repo || echo "Already in state or import failed"
          else
            echo "Artifact registry does not exist. Will be created."
            terraform state rm google_artifact_registry_repository.myapp_repo || true
          fi
          
          # Add more resources as needed (VPC, subnets, IAM roles, etc.)
          EOF
          
          chmod +x import_resources.sh
          ./import_resources.sh
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-sa-key.json

      # Step 7: Refresh Terraform State
      - name: Refresh Terraform State
        run: |
          cd terraform
          terraform refresh
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-sa-key.json

      # Step 8: Terraform Plan
      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -no-color -input=false
        continue-on-error: true
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-sa-key.json

      # Step 9: Apply Terraform
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd terraform
          terraform apply -auto-approve -input=false
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-sa-key.json

  build-push:
    name: "Build & Push Docker Images"
    needs: terraform-setup
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Configure Docker for Google Artifact Registry
      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Step 4: Check if validator-api image already exists
      - name: Check if validator-api image exists
        id: validator-check
        run: |
          if gcloud artifacts docker images describe us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/validator-api:$GITHUB_SHA --quiet; then
            echo "Image already exists. Skipping build."
            echo "image_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Image does not exist. Will build."
            echo "image_exists=false" >> $GITHUB_OUTPUT
          fi

      # Step 5: Build Validator API Docker Image if it doesn't exist
      - name: Build Validator API Docker Image
        if: steps.validator-check.outputs.image_exists == 'false'
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/validator-api:$GITHUB_SHA \
          -f validator_api/Dockerfile validator_api/

      # Step 6: Push Validator API Docker Image if it doesn't exist
      - name: Push Validator API Docker Image
        if: steps.validator-check.outputs.image_exists == 'false'
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/validator-api:$GITHUB_SHA

      # Step 7: Check if processor-api image already exists
      - name: Check if processor-api image exists
        id: processor-check
        run: |
          if gcloud artifacts docker images describe us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/processor-api:$GITHUB_SHA --quiet; then
            echo "Image already exists. Skipping build."
            echo "image_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Image does not exist. Will build."
            echo "image_exists=false" >> $GITHUB_OUTPUT
          fi

      # Step 8: Build Processor API Docker Image if it doesn't exist
      - name: Build Processor API Docker Image
        if: steps.processor-check.outputs.image_exists == 'false'
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/processor-api:$GITHUB_SHA \
          -f processor_api/Dockerfile processor_api/

      # Step 9: Push Processor API Docker Image if it doesn't exist
      - name: Push Processor API Docker Image
        if: steps.processor-check.outputs.image_exists == 'false'
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/processor-api:$GITHUB_SHA

  deploy-gke:
    name: "Deploy to GKE"
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Install Google Cloud SDK
      - name: Install Google Cloud SDK
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk

      # Step 4: Install gke-gcloud-auth-plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      # Step 5: Configure kubectl to use gke-gcloud-auth-plugin
      - name: Configure kubectl to use gke-gcloud-auth-plugin
        run: |
          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      # Step 6: Connect to GKE Cluster
      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials myapp-gke-cluster --zone us-central1-a --project ${{ secrets.PROJECT_ID }}

      # Step 7: Update deployments with the new image tag
      - name: Update Kubernetes Manifests
        run: |
          # Update validator-api deployment image
          sed -i "s|image: us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/validator-api:.*|image: us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/validator-api:$GITHUB_SHA|g" k8s/validator_api/validator-deployment.yaml
          
          # Update processor-api deployment image
          sed -i "s|image: us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/processor-api:.*|image: us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/processor-api:$GITHUB_SHA|g" k8s/processor_api/processor-deployment.yaml

      # Step 8: Apply Kubernetes Resources
      - name: Apply Kubernetes Resources
        run: |
          # Create namespace if it doesn't exist
          kubectl get namespace myapp || kubectl apply -f k8s/namespace.yaml
          
          # Apply each resource with proper error handling
          for resource in k8s/persistent-volume.yaml k8s/persistent-volume-claim.yaml k8s/config-map.yaml k8s/validator_api/validator-deployment.yaml k8s/processor_api/processor-deployment.yaml; do
            echo "Applying $resource..."
            kubectl apply -f $resource || echo "Failed to apply $resource, continuing..."
          done
          
          # Wait for deployments to be ready
          kubectl rollout status deployment/validator-api -n myapp --timeout=5m || echo "Validator API deployment not ready within timeout, check status manually"
          kubectl rollout status deployment/processor-api -n myapp --timeout=5m || echo "Processor API deployment not ready within timeout, check status manually"