name: Terraform Setup, Build, Push to GAR, and Deploy GKE

on:
  push:
    branches:
      - main

jobs:
  terraform-setup:
    name: "Setup Infrastructure with Terraform"
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ Step 2: Setup Google Cloud Credentials
      - name: Setup Google Cloud Credentials
        run: echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-sa-key.json

      # ✅ Step 3: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ✅ Step 4: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # ✅ Step 5: Initialize Terraform
      - name: Terraform Init
        run: |
          cd terraform
          terraform init -backend-config="bucket=${{ secrets.TF_BUCKET }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-sa-key.json

      # ✅ Step 6: Check if Resources Already Exist
      - name: Check if Resources Already Exist
        id: check-resources
        run: |
          cd terraform
          if gcloud artifacts repositories describe myapp-repo --location=us-central1 > /dev/null 2>&1; then
            echo "Artifact Registry repository already exists."
            echo "artifact_registry_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Artifact Registry repository does not exist."
            echo "artifact_registry_exists=false" >> $GITHUB_OUTPUT
          fi

          if gcloud container clusters describe myapp-gke-cluster --region us-central1 > /dev/null 2>&1; then
            echo "GKE cluster already exists."
            echo "gke_cluster_exists=true" >> $GITHUB_OUTPUT
          else
            echo "GKE cluster does not exist."
            echo "gke_cluster_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-sa-key.json

      # ✅ Step 7: Terraform Plan (Only if Resources Do Not Exist)
      - name: Terraform Plan
        if: steps.check-resources.outputs.artifact_registry_exists == 'false' || steps.check-resources.outputs.gke_cluster_exists == 'false'
        run: |
          cd terraform
          terraform plan -no-color -input=false
        continue-on-error: true

      # ✅ Step 8: Apply Terraform (Only if Resources Do Not Exist)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && (steps.check-resources.outputs.artifact_registry_exists == 'false' || steps.check-resources.outputs.gke_cluster_exists == 'false')
        run: |
          cd terraform
          terraform apply -auto-approve -input=false
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-sa-key.json

  build-push:
    name: "Build & Push Docker Images"
    needs: terraform-setup  # ✅ Runs only after Terraform completes
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ✅ Step 3: Configure Docker for Google Artifact Registry
      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # ✅ Step 4: Build Validator API Docker Image
      - name: Build Validator API Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/validator-api:$GITHUB_SHA \
          -f validator_api/Dockerfile validator_api/

      # ✅ Step 5: Push Validator API Docker Image
      - name: Push Validator API Docker Image
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/validator-api:$GITHUB_SHA

      # ✅ Step 6: Build Processor API Docker Image
      - name: Build Processor API Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/processor-api:$GITHUB_SHA \
          -f processor_api/Dockerfile processor_api/

      # ✅ Step 7: Push Processor API Docker Image
      - name: Push Processor API Docker Image
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/processor-api:$GITHUB_SHA

  deploy-gke:
    name: "Deploy to GKE"
    needs: build-push  # ✅ Runs only after Docker images are pushed
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ✅ Step 3: Connect to GKE Cluster
      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials myapp-gke-cluster --region us-central1

      # ✅ Step 4: Update Kubernetes Deployments
      - name: Update Kubernetes Deployments
        run: |
          kubectl set image deployment/validator-api validator-api=us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/validator-api:$GITHUB_SHA
          kubectl set image deployment/processor-api processor-api=us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/myapp-repo/processor-api:$GITHUB_SHA